(()=>{'use strict';
const META=window.VALHEIM_MAP_META||{}, RAW=window.NOoo_LOCATIONS||[],$=id=>document.getElementById(id);
const canvas=$('mapCanvas'),wrap=$('mapWrap'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const FULL=Number(META.width||4096), TILE=Number(META.tileSize||512), WORLD_RADIUS=10000, DISC_SCALE=0.818, MAP_CX=FULL/2, MAP_CY=FULL/2, MAP_R=FULL*0.5*DISC_SCALE, LEVELS=(META.levels||[]).slice().sort((a,b)=>a.scale-b.scale);
let view={scale:1,tx:0,ty:0},fitScale=1,drag=false,moved=false,last={x:0,y:0},pending=false,selected=null,hover=null,search='',hit=[];
const BOSS=new Set(['Eikthyrnir','GDKing','Bonemass','Dragonqueen','GoblinKing','FaderLocation','Mistlands_DvergrBossEntrance1']);
const TRADER=new Set(['Vendor_BlackForest','BogWitch_Camp']);
const DUNGEON=new Set(['Crypt2','Crypt3','Crypt4','SunkenCrypt4','TrollCave02','MountainCave02','Mistlands_DvergrTownEntrance1','Mistlands_DvergrTownEntrance2','Hildir_cave','Hildir_crypt','Hildir_plainsfortress']);
const FRIENDLY={StartTemple:'Spawn',Eikthyrnir:'Eikthyr',GDKing:'The Elder',Bonemass:'Bonemass',Dragonqueen:'Moder',GoblinKing:'Yagluth',FaderLocation:'Fader',Mistlands_DvergrBossEntrance1:'The Queen — Entrance',Vendor_BlackForest:'Haldor',BogWitch_Camp:'Bog Witch',Hildir_camp:'Hildir — Camp',Crypt2:'Burial Chamber',Crypt3:'Burial Chamber',Crypt4:'Burial Chamber',SunkenCrypt4:'Sunken Crypt',TrollCave02:'Troll Cave',MountainCave02:'Frost Cave',Mistlands_DvergrTownEntrance1:'Infested Mine',Mistlands_DvergrTownEntrance2:'Infested Mine',Hildir_cave:'Hildir — Howling Cavern',Hildir_crypt:'Hildir — Smouldering Tomb',Hildir_plainsfortress:'Hildir — Sealed Tower',MorgenHole1:'Morgen Cave',MorgenHole2:'Morgen Cave',MorgenHole3:'Morgen Cave',TarPit1:'Tar Pit',TarPit2:'Tar Pit',TarPit3:'Tar Pit'};
const ALIASES={Mistlands_DvergrTownEntrance1:'infested mine mina infestada dungeon mistlands grappling hook gancho',Mistlands_DvergrTownEntrance2:'infested mine mina infestada dungeon mistlands grappling hook gancho',Crypt2:'burial chamber tumulo camara sepulcral dungeon black forest floresta negra',Crypt3:'burial chamber tumulo camara sepulcral dungeon black forest floresta negra',Crypt4:'burial chamber tumulo camara sepulcral dungeon black forest floresta negra',SunkenCrypt4:'sunken crypt cripta pantano swamp dungeon',TrollCave02:'troll cave caverna troll dungeon',MountainCave02:'frost cave caverna gelo mountain montanha dungeon',Vendor_BlackForest:'haldor merchant trader mercador',BogWitch_Camp:'bog witch bruxa swamp trader mercador',Hildir_camp:'hildir trader mercador'};
const COLORS={spawn:'#f5f7fa',boss:'#f06a66',trader:'#efbd50',dungeon:'#9d6bd7',dvergr:'#55c4b0',hildir:'#eaa0cd',runestone:'#62a2e9',ashlands:'#f07852',other:'#9aa9ba'};
const LABELS={spawn:'Spawn',boss:'Bosses',trader:'Traders',dungeon:'Dungeons',dvergr:'Dvergr / Mistlands',hildir:'Hildir',runestone:'Runestones',ashlands:'Ashlands',other:'Outros'};
const ORDER=['spawn','boss','trader','dungeon','dvergr','hildir','runestone','ashlands','other'];
function category(p){if(p==='StartTemple')return'spawn';if(BOSS.has(p))return'boss';if(TRADER.has(p))return'trader';if(/^Hildir_/.test(p))return'hildir';if(DUNGEON.has(p))return'dungeon';if(/^Runestone_/.test(p))return'runestone';if(/^Mistlands_/.test(p))return'dvergr';if(/^(Fader|Charred|Ashland|Morgen|PlaceofMystery|Sulfur|Volture|LeviathanLava)/.test(p))return'ashlands';return'other'}
function pretty(p){return FRIENDLY[p]||String(p).replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/([A-Za-z])(\d+)$/,'$1 $2').replace(/\s+/g,' ').trim()}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
const LOCS=RAW.map(r=>{const p=r[0],cat=category(p),label=pretty(p);return{prefab:p,x:+r[1],y:+r[2],z:+r[3],cat,label,hay:norm(label+' '+p+' '+(ALIASES[p]||'')+' '+cat)}});
const enabled=new Set(['spawn','boss','trader','dungeon']);
const iconSvg={
spawn:'<path d="M12 1.8l2.2 6 6 2.2-6 2.2-2.2 6-2.2-6-6-2.2 6-2.2z" fill="white"/><circle cx="12" cy="12" r="2" fill="#111827"/>',
boss:'<path d="M5 10a7 7 0 1 1 14 0v4.5c0 1.4-1.1 2.5-2.5 2.5H15v3h-2v-3h-2v3H9v-3H7.5A2.5 2.5 0 0 1 5 14.5z" fill="white"/><circle cx="9" cy="10.5" r="1.5" fill="#111827"/><circle cx="15" cy="10.5" r="1.5" fill="#111827"/>',
trader:'<path d="M7 8h10l2 11H5L7 8z" fill="white"/><path d="M9 8c0-3 6-3 6 0" fill="none" stroke="white" stroke-width="2"/><circle cx="12" cy="13.5" r="2.2" fill="#6b4a12"/>',
burial:'<path d="M4 20V10a8 8 0 0 1 16 0v10H4z" fill="white"/><path d="M8 20v-9a4 4 0 0 1 8 0v9" fill="#111827"/><path d="M4 13h4M16 13h4" stroke="#111827" stroke-width="1.3"/>',
cave:'<path d="M2.5 20L7 8l5-5 5 5 4.5 12H2.5z" fill="white"/><path d="M7.5 20c.3-5 2-8 4.5-8s4.2 3 4.5 8" fill="#111827"/>',
crypt:'<path d="M4 8l8-5 8 5v2H4V8zM5 11h3v8H5zM10.5 11h3v8h-3zM16 11h3v8h-3zM3 20h18v2H3z" fill="white"/>',
frost:'<path d="M12 2v20M3.3 7l17.4 10M3.3 17l17.4-10M8 4.3L12 7l4-2.7M8 19.7l4-2.7 4 2.7" stroke="white" stroke-width="1.8" stroke-linecap="round" fill="none"/>',
infested:'<path d="M5 20V11a7 7 0 0 1 14 0v9" fill="none" stroke="white" stroke-width="2.2"/><path d="M7 5l10 14M17 5L7 19" stroke="white" stroke-width="2.1" stroke-linecap="round"/><circle cx="12" cy="11" r="2.3" fill="#111827" stroke="white" stroke-width="1.3"/>',
tower:'<path d="M6 3h3v3h6V3h3v5l-2 2v11H8V10L6 8V3z" fill="white"/><path d="M11 21v-6h2v6" fill="#111827"/>',
runestone:'<path d="M8 21L7 7l3-4h5l2 4-1 14H8z" fill="white"/><path d="M11 8l3 2-3 2 3 3" fill="none" stroke="#111827" stroke-width="1.7" stroke-linecap="round"/>',
flame:'<path d="M13 2c1 5-3 6-1 9 1-3 4-3 5-6 4 5 4 9 2 13-1.5 3-4 4-7 4-5 0-8-3-8-7 0-4 3-7 6-10 0 4 2 4 3 5 1-2 2-4 0-8z" fill="white"/>',
pin:'<path d="M12 22s7-7.2 7-13A7 7 0 1 0 5 9c0 5.8 7 13 7 13z" fill="white"/><circle cx="12" cy="9" r="2.4" fill="#111827"/>'};
const iconImgs={};function makeIcon(k){if(iconImgs[k])return iconImgs[k];const im=new Image();im.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">${iconSvg[k]||iconSvg.pin}</svg>`);im.onload=drawSoon;return iconImgs[k]=im}Object.keys(iconSvg).forEach(makeIcon);
function iconKey(l){const p=l.prefab;if(p==='StartTemple')return'spawn';if(BOSS.has(p))return'boss';if(TRADER.has(p)||p==='Hildir_camp')return'trader';if(/^Crypt[234]$/.test(p))return'burial';if(p==='TrollCave02')return'cave';if(p==='SunkenCrypt4')return'crypt';if(p==='MountainCave02'||p==='Hildir_cave')return'frost';if(/^Mistlands_DvergrTownEntrance[12]$/.test(p))return'infested';if(/^Runestone_/.test(p))return'runestone';if(l.cat==='ashlands')return'flame';if(l.cat==='dvergr')return'tower';return'pin'}
function counts(){const c={};for(const l of LOCS)c[l.cat]=(c[l.cat]||0)+1;return c}function rebuildCats(){const c=counts(),box=$('categoryList');box.innerHTML='';for(const k of ORDER){if(!c[k])continue;const row=document.createElement('label');row.className='cat-row';row.innerHTML=`<input type="checkbox" data-cat="${k}" ${enabled.has(k)?'checked':''}><span><i class="cat-dot" style="background:${COLORS[k]}"></i>&nbsp; ${LABELS[k]}</span><span class="cat-count">${c[k]}</span>`;box.appendChild(row)}box.querySelectorAll('input').forEach(el=>el.onchange=()=>{el.checked?enabled.add(el.dataset.cat):enabled.delete(el.dataset.cat);updateResults();drawSoon()})}
function visible(l){const q=norm(search);return q?l.hay.includes(q):enabled.has(l.cat)}function shown(){return LOCS.filter(visible)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateResults(){const a=shown(),box=$('resultList');$('resultCount').textContent=a.length.toLocaleString('pt-BR');box.innerHTML='';if(!a.length){box.innerHTML='<div class="empty">Nenhum pin com esses filtros.</div>';return}for(const l of a.slice(0,250)){const b=document.createElement('button');b.className='result-item';b.innerHTML=`<div class="r-name">${esc(l.label)}</div><div class="r-meta">${esc(LABELS[l.cat])} • x ${Math.round(l.x)}, z ${Math.round(l.z)}</div>`;b.onclick=()=>focusLoc(l);box.appendChild(b)}if(a.length>250){const d=document.createElement('div');d.className='empty';d.textContent=`+ ${a.length-250} resultados — refine a busca`;box.appendChild(d)}}
function resize(){const r=wrap.getBoundingClientRect(),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}drawSoon()}
function worldToImage(x,z){return{x:MAP_CX+(x/WORLD_RADIUS)*MAP_R,y:MAP_CY-(z/WORLD_RADIUS)*MAP_R}}function imageToWorld(px,py){return{x:((px-MAP_CX)/MAP_R)*WORLD_RADIUS,z:-((py-MAP_CY)/MAP_R)*WORLD_RADIUS}}function screenToImage(x,y){return{x:(x-view.tx)/view.scale,y:(y-view.ty)/view.scale}}function imageToScreen(x,y){return{x:x*view.scale+view.tx,y:y*view.scale+view.ty}}
function fit(){const rp=MAP_R,margin=26;fitScale=Math.min((canvas.width-2*margin)/(2*rp),(canvas.height-2*margin)/(2*rp));view.scale=fitScale;view.tx=canvas.width/2-MAP_CX*view.scale;view.ty=canvas.height/2-MAP_CY*view.scale;drawSoon()}
const cache=new Map(),CACHE_MAX=32;function tilePath(l,x,y){return l.path.replace('{x}',x).replace('{y}',y)}function getTile(l,x,y){const k=l.index+':'+x+':'+y;if(cache.has(k)){const im=cache.get(k);cache.delete(k);cache.set(k,im);return im}const im=new Image();im.decoding='async';im.src=tilePath(l,x,y);im.onload=drawSoon;cache.set(k,im);while(cache.size>CACHE_MAX)cache.delete(cache.keys().next().value);return im}
function chooseLevel(){let out=LEVELS[LEVELS.length-1];for(const l of LEVELS){if(l.scale>=view.scale){out=l;break}}return out}function drawTiles(){const l=chooseLevel();if(!l)return;const left=Math.max(0,(0-view.tx)/view.scale),top=Math.max(0,(0-view.ty)/view.scale),right=Math.min(FULL,(canvas.width-view.tx)/view.scale),bottom=Math.min(FULL,(canvas.height-view.ty)/view.scale);if(right<=left||bottom<=top)return;const x0=Math.max(0,Math.floor(left*l.scale/TILE)),y0=Math.max(0,Math.floor(top*l.scale/TILE)),x1=Math.min(l.cols-1,Math.floor(right*l.scale/TILE)),y1=Math.min(l.rows-1,Math.floor(bottom*l.scale/TILE));ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const im=getTile(l,x,y);if(!im.complete||!im.naturalWidth)continue;const fx=x*TILE/l.scale,fy=y*TILE/l.scale,fw=im.naturalWidth/l.scale,fh=im.naturalHeight/l.scale;ctx.drawImage(im,fx*view.scale+view.tx,fy*view.scale+view.ty,fw*view.scale,fh*view.scale)}$('qualityHud').textContent=`${l.width}² • cache ${cache.size}`}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawPin(l,s,ratio){const sel=l===selected;let size=ratio<1.8?0:ratio<3.2?14:ratio<6?18:20;if(l.cat==='spawn'||l.cat==='boss'||l.cat==='trader')size=Math.max(size,18);if(!size){const r=sel?5:2.4;ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.fillStyle=sel?'#fff':COLORS[l.cat];ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='#081017';ctx.stroke();return Math.max(9,r+2)}const q=size+6+(sel?4:0),x=s.x-q/2,y=s.y-q/2;ctx.beginPath();ctx.arc(s.x,s.y,q/2,0,Math.PI*2);ctx.fillStyle=sel?'#f5f8fb':'#0b1118e8';ctx.fill();ctx.lineWidth=sel?2.6:2;ctx.strokeStyle=COLORS[l.cat];ctx.stroke();const im=makeIcon(iconKey(l));if(im.complete&&im.naturalWidth){const is=size*(sel?1.05:1);ctx.drawImage(im,s.x-is/2,s.y-is/2,is,is)}return q/2+2}
function drawSoon(){if(pending)return;pending=true;requestAnimationFrame(draw)}function draw(){pending=false;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#03060a';ctx.fillRect(0,0,canvas.width,canvas.height);drawTiles();hit=[];const a=shown(),ratio=view.scale/fitScale;for(const l of a){const p=worldToImage(l.x,l.z),s=imageToScreen(p.x,p.y);if(s.x<-30||s.y<-30||s.x>canvas.width+30||s.y>canvas.height+30)continue;const r=drawPin(l,s,ratio);hit.push({l,x:s.x,y:s.y,r:Math.max(10,r)})}$('zoomHud').textContent=Math.round(ratio*100)+'%'}
function nearest(x,y,max=18){let best=null,bd=max*max;for(const q of hit){const d=(q.x-x)**2+(q.y-y)**2,lim=Math.max(max,q.r);if(d<bd&&d<lim*lim){bd=d;best=q.l}}return best}function tooltip(l,x,y){const t=$('tooltip');if(!l){t.classList.add('hidden');return}t.innerHTML=`<strong>${esc(l.label)}</strong><div class="tip-meta">${esc(LABELS[l.cat])}<br>x ${Math.round(l.x)} &nbsp; y ${Math.round(l.y)} &nbsp; z ${Math.round(l.z)}</div><div class="tip-prefab">${esc(l.prefab)}</div>`;t.style.left=Math.min(canvas.width-315,Math.max(8,x+10))+'px';t.style.top=Math.min(canvas.height-110,Math.max(8,y+10))+'px';t.classList.remove('hidden')}
function focusLoc(l){selected=l;const p=worldToImage(l.x,l.z),target=Math.max(view.scale,fitScale*7);view.scale=Math.min(fitScale*18,target);view.tx=canvas.width/2-p.x*view.scale;view.ty=canvas.height/2-p.y*view.scale;tooltip(l,canvas.width/2+10,canvas.height/2-10);drawSoon()}function zoomAt(f,x,y){const p=screenToImage(x,y),ns=Math.max(fitScale*.75,Math.min(fitScale*18,view.scale*f));view.scale=ns;view.tx=x-p.x*ns;view.ty=y-p.y*ns;drawSoon()}
canvas.onwheel=e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoomAt(e.deltaY<0?1.15:.87,e.clientX-r.left,e.clientY-r.top)};canvas.onmousedown=e=>{if(e.button!==0)return;drag=true;moved=false;last={x:e.clientX,y:e.clientY};canvas.classList.add('dragging');tooltip(null)};window.onmousemove=e=>{const r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;if(drag){const dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.abs(dx)+Math.abs(dy)>1)moved=true;view.tx+=dx;view.ty+=dy;last={x:e.clientX,y:e.clientY};drawSoon();return}if(sx>=0&&sy>=0&&sx<canvas.width&&sy<canvas.height){const p=screenToImage(sx,sy),w=imageToWorld(p.x,p.y);$('coordHud').textContent=`x ${Math.round(w.x)}   z ${Math.round(w.z)}`;const n=nearest(sx,sy,14);if(n!==hover){hover=n;if(n)tooltip(n,sx,sy);else if(!selected)tooltip(null)}}};window.onmouseup=()=>{drag=false;canvas.classList.remove('dragging')};canvas.onclick=e=>{if(moved){moved=false;return}const r=canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,n=nearest(sx,sy,18);selected=n;if(n)tooltip(n,sx,sy);else tooltip(null);drawSoon()};
$('zoomIn').onclick=()=>zoomAt(1.3,canvas.width/2,canvas.height/2);$('zoomOut').onclick=()=>zoomAt(.77,canvas.width/2,canvas.height/2);$('fitWorld').onclick=fit;$('searchInput').oninput=e=>{search=e.target.value;updateResults();drawSoon()};$('clearSearch').onclick=()=>{$('searchInput').value='';search='';updateResults();drawSoon()};$('allOffBtn').onclick=()=>{enabled.clear();document.querySelectorAll('#categoryList input').forEach(x=>x.checked=false);updateResults();drawSoon()};$('collapseBtn').onclick=()=>{$('sidebar').classList.add('hidden');$('showSidebar').classList.remove('hidden');resize()};$('showSidebar').onclick=()=>{$('sidebar').classList.remove('hidden');$('showSidebar').classList.add('hidden');resize()};$('helpBtn').onclick=()=>$('helpModal').classList.remove('hidden');$('closeHelp').onclick=()=>$('helpModal').classList.add('hidden');$('helpModal').onclick=e=>{if(e.target===$('helpModal'))$('helpModal').classList.add('hidden')};window.onresize=()=>{resize();fit()};rebuildCats();updateResults();resize();fit();})();